micronaut:
  server:
    port: ${HTTP_PORT:8080}

  application:
    name: awsTraining
datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    dialect: ${DB_DIALECT:POSTGRES}

jpa.default.properties.hibernate.hbm2ddl.auto: ${JPA_DLL_AUTO:update}

endpoints:
  all:
    sensitive: ${HTTP_SENSITIVE:true}
  health:
    enabled: ${HEALTH_ENABLED:true}
    sensitive: ${HEALTH_SENSITIVE:false}
    details-visible: ${HEALTH_DETAILS_VISIBLE:ANONYMOUS}
